### ISSUE TITLE
Feature Request: possible to hide/show channels based on configuration

### ISSUE THREAD

**Issue by ChrisMisker** [arjenbos/ha_alpha_innotec#16]
Great new feature to be able to see the state of the valves. I love it! Love the enthusiasm of the developer as well, thanks!

A feature request: is it possible to automatically show or hide the channels, based upon if they are configured or not? The Alpha Home valves always have 8 channels, but not all are used. If not used, the API does return a value, but it does nothing. So is it possible to hide these channels, when not configured?

**Comment by arjenbos** [comment]
If an integration is already setup, then an integration can't disable entities. This can only be done on creation - https://developers.home-assistant.io/docs/entity_registry_disabled_by/#integrations-setting-default-value-of-disabled_by-for-new-entity-registry-entries.

**Comment by arjenbos** [comment]
What do you think https://github.com/arjenbos/ha_alpha_innotec/pull/18 ?

I didn't add the valves to a device, because (if I understand HA concept correctly) every "device" can live in an "area". A thermostat is a device, and a distributor is a device. A distributor has multiple valves (the sensors), but it can live in another area than the thermostat.

If you want to link a valve to an area, then you can change this in the settings of the sensor.
